[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Maze"
description = "Maze generator and interactive game"
requires-python = ">=3.12"
version = "0.2"
classifiers = ["Private :: Do Not Upload"]
authors = [{ "name" = "Jennifer Richards", "email" = "jeni@borkbork.org" }]
dependencies = [
    "cycler==0.12.1",
    "matplotlib==3.10.8",
    "numpy==2.4.2",
    "papersize==1.2.0",
    "pyparsing==3.3.2",
    "python-dateutil==2.9.0",
    "pytz==2025.2",
    "setuptools==82.0.0",
    "subprocess32==3.5.4",
    "tqdm==4.67.3",
]

[project.scripts]
mazegen = "maze.gen:main"